<?php
	$_lang = array_merge(
		array (
  'area_mpdf_document' => 'Документ',
  'area_mpdf_main' => 'Основные',
  'area_mpdf_pdf' => 'PDF',
  'area_mpdf_protection' => 'Защита',
  'area_mpdf_tpl' => 'Чанки',
  'area_mpdf_tv' => 'Дополнительные поля',
  'setting_mpdf.author' => 'Автор PDF',
  'setting_mpdf.author_desc' => 'Имя автора документа. Эти метаданные можно увидеть при проверке свойств документа в Adobe Reader.',
  'setting_mpdf.configuration' => 'Конфигурация mPDF',
  'setting_mpdf.configuration_desc' => 'Содержимое Конфигураций mPDF должно содержать массив в кодировке JSON с параметрами, которые вы хотите изменить. Документации mPDF: <a href="https://mpdf.github.io/configuration/configuration-v7-x.html#constructor-configuration" target="_blank">Constructor configuration</a> и <a href="https://mpdf.github.io/reference/mpdf-variables/overview.html" target="_blank">All configuration variables</a>',
  'setting_mpdf.creator' => 'Создатель PDF',
  'setting_mpdf.creator_desc' => 'Имя создатель документа. Эти метаданные можно увидеть при проверке свойств документа в Adobe Reader.',
  'setting_mpdf.defaultFont' => 'Шрифт документа PDF по умолчанию',
  'setting_mpdf.defaultFontSize' => 'Размер шрифта документа PDF по умолчанию',
  'setting_mpdf.fontData' => 'Имена шрифтов',
  'setting_mpdf.fontData_desc' => 'Содержимое должно содержать массив в кодировке JSON. Документации mPDF: <a href="https://mpdf.github.io/fonts-languages/fonts-in-mpdf-7-x.html" target="_blank">Fonts</a>',
  'setting_mpdf.fontDirs' => 'Каталог шрифтов',
  'setting_mpdf.fontDirs_desc' => 'Содержимое должно содержать массив в кодировке JSON. Документации mPDF: <a href="https://mpdf.github.io/fonts-languages/fonts-in-mpdf-7-x.html" target="_blank">Fonts</a>',
  'setting_mpdf.format' => 'Формат документа PDF',
  'setting_mpdf.format_desc' => 'Может быть указан либо как предопределенный размер страницы, либо как массив ширины и высоты в миллиметрах. Документации mPDF: <a href="https://mpdf.github.io/reference/mpdf-functions/construct.html">Format</a>',
  'setting_mpdf.marginBottom' => 'Отступ от нижнего края',
  'setting_mpdf.marginBottom_desc' => 'Отступ от нижнего края докемента PDF.',
  'setting_mpdf.marginFooter' => 'Отступ Footer от нижнего края',
  'setting_mpdf.marginFooter_desc' => 'Отступ нижнего колонтитула документа PDF.',
  'setting_mpdf.marginHeader' => 'Отступ Header от верхнего края',
  'setting_mpdf.marginHeader_desc' => 'Отступ верхнего колонтитула документа PDF.',
  'setting_mpdf.marginLeft' => 'Отступ от левого края',
  'setting_mpdf.marginLeft_desc' => 'Отступ от левого края документа PDF.',
  'setting_mpdf.marginRight' => 'Отступ от правого края',
  'setting_mpdf.marginRight_desc' => 'Отступ от правого края документа PDF.',
  'setting_mpdf.marginTop' => 'Отступ от верхнего края',
  'setting_mpdf.marginTop_desc' => 'Отступ от верхнего края документа PDF.',
  'setting_mpdf.mode' => 'Режим документа PDF',
  'setting_mpdf.mode_desc' => 'Режим документа PDF или Кодировка документа PDF. Документации mPDF: <a href="https://mpdf.github.io/reference/mpdf-functions/construct.html#variables-with-defaults-from-constructor" target="_blank">mode</a> и <a href="https://mpdf.github.io/fonts-languages/choosing-a-configuration-v7-x.html" target="_blank">Configuration</a>.',
  'setting_mpdf.orientation' => 'Ориентация PDF',
  'setting_mpdf.orientation_desc' => 'Этот атрибут определяет ориентацию страницы по умолчанию для нового документа. Документации mPDF: <a href="https://mpdf.github.io/reference/mpdf-functions/construct.html">Format</a>',
  'setting_mpdf.ownerPassword' => 'Пароль администратора',
  'setting_mpdf.ownerPassword_desc' => 'Укажите пароль, который обеспечит полный доступ и разрешения к PDF-файлу.',
  'setting_mpdf.pdfCSS' => 'Путь к CSS файл',
  'setting_mpdf.pdfCSS_desc' => 'Абсолютный путь к CSS файл. Пример: css/style.css',
  'setting_mpdf.pdfPath' => 'Абсолютный путь к PDF',
  'setting_mpdf.pdfPath_desc' => 'Абсолютный путь к PDF. Пример: {assets_path}pdf/',
  'setting_mpdf.pdfUrl' => 'Относительный путь к PDF',
  'setting_mpdf.pdfUrl_desc' => 'Относительный путь к PDF. Пример: {assets_path}pdf/',
  'setting_mpdf.permissions' => 'Список Права доступа',
  'setting_mpdf.permissions_desc' => 'Содержимое должно содержать массив в кодировке JSON. Документации mPDF: <a href="https://mpdf.github.io/reference/mpdf-functions/setprotection.html#parameters" target="_blank">Permissions</a>.',
  'setting_mpdf.processTVs' => 'Вывести обработанные TV',
  'setting_mpdf.processTVs_desc' => 'При включённом параметре будут обработаны все TV.',
  'setting_mpdf.title' => 'Заголовок PDF',
  'setting_mpdf.title_desc' => 'Заголовок для документа. Заголовок отображается в верхней части экрана Adobe Reader при просмотре файла PDF и включен в метаданные документа, которые можно увидеть при проверке свойств документа в Adobe Reader.',
  'setting_mpdf.tpl' => 'Имя чанка для HTML',
  'setting_mpdf.tplFooter' => 'Имя чанка для Footer',
  'setting_mpdf.tplFooter_desc' => 'Имя чанка для оформления нижнего колонтитула документа PDF.',
  'setting_mpdf.tplHeader' => 'Имя чанка для Header',
  'setting_mpdf.tplHeader_desc' => 'Имя чанка для оформления верхнего колонтитула документа PDF.',
  'setting_mpdf.tpl_desc' => 'Имя чанка для оформления документа PDF.',
  'setting_mpdf.tvPDF' => 'Имя TV параметра c создание PDF',
  'setting_mpdf.tvPDF_desc' => 'Содержимое TV должно содержать активатор. При сохранение ресурса создаёт PDF.',
  'setting_mpdf.tvPDFlive' => 'Имя TV параметра c создание PDF на лету',
  'setting_mpdf.tvPDFlive_desc' => 'Содержимое TV должно содержать активатор. При открытие страницы выводить PDF.',
  'setting_mpdf.tvPDFoptions' => 'Имя TV параметра c параметрами mPDF',
  'setting_mpdf.tvPDFoptions_desc' => 'Содержимое TV должно содержать объект в кодировке JSON с параметрами, которые вы хотите изменить.',
  'setting_mpdf.tvPrefix' => 'Префикс для TV плейсхолдеров.',
  'setting_mpdf.tvPrefix_desc' => 'Укажите префикс для добавление к имени TV. Например: "tv."',
  'setting_mpdf.userPassword' => 'Пароль пользователя',
  'setting_mpdf.userPassword_desc' => 'Укажите пароль, необходимый пользователю для открытия PDF-файла.',
)
		, $_lang);
	